name: ServerMenu
main: DataLion\ServerMenu\Main
version: 1.0.0
api: 3.9.8
author: DataLion

description: Server Transfer Menu


website: https://github.com/DataLiontje/ServerMenu

commands:
 servermenu:
  description: Server menu main command.
  usage: /servermenu
  permission: servermenu.command
  aliases: ["serverm", "smenu"]

permissions:
 servermenu.command:
  description: Server menu main permission
  default: true
